<h2>Soal 1: Membuat Objek DataFrames</h2>

- Buatlah objek dataframes dari objek dictionary, Bebas!

In [2]:
# Membuat dataframes dari dictionary
import pandas as pd

Daftar_hadir={'Nama':['Andi', 'Sisi','Sari','Didi','Weni','Citra'],
              'Izin' : [2,1,0,3,0,1],
             'Sakit':[0,0,3,0,1,0],
             'Alpa':[2,1,0,0,1,2]}

pd.DataFrame(Daftar_hadir)

    Nama  Izin  Sakit  Alpa
0   Andi     2      0     2
1   Sisi     1      0     1
2   Sari     0      3     0
3   Didi     3      0     0
4   Weni     0      1     1
5  Citra     1      0     2

<h2>Soal 2: Membaca data dari file</h2>

Download file bernama [diamonds.csv](https://drive.google.com/uc?export=download&id=1qQiM9utQUThTPq8jk8stPMh_y2zfqYOd), kemudian baca data tersebut dan assign ke dalam suatu variabel kemudian print.

In [11]:
# Membaca data dan memasukannya kedalam suatu variabel
data=pd.read_csv('diamonds-1.csv')
pd.read_csv('diamonds-1.csv')

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
5,6,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48
6,7,0.24,Very Good,I,VVS1,62.3,57.0,336,3.95,3.98,2.47
7,8,0.26,Very Good,H,SI1,61.9,55.0,337,4.07,4.11,2.53
8,9,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49
9,10,0.23,Very Good,H,VS1,59.4,61.0,338,4.00,4.05,2.39
10,11,0.30,Good,J,SI1,64.0,55.0,339,4.25,4.28,2.73
11,12,0.23,Ideal,J,VS1,62.8,56.0,340,3.93,3.90,2.46
12,13,0.22,Premium,F,SI1,60.4,61.0,342,3.88,3.84,2.33
13,14,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71
14,15,0.20,Premium,E,SI2,60.2,62.0,345,3.79,3.75,2.27
15,16,0.32,Premium,E,I1,60.9,58.0,345,4.38,4.42,2.68
16,17,0.30,Ideal,I,SI2,62.0,54.0,348,4.31,4.34,2.68
17,18,0.30,Good,J,SI1,63.4,54.0,351,4.23,4.29,2.70
18,19,0.30,Good,J,SI1,63.8,56.0,351,4.23,4.26,2.71
19,20,0.30,Very Good,J,SI1,62.7,59.0,351,4.21,4.27,2.66
20,21,0.30,Good,I,SI2,63.3,56.0,351,4.26,4.30,2.71
21,22,0.23,Very Good,E,VS2,63.8,55.0,352,3.85,3.92,2.48
22,23,0.23,Very Good,H,VS1,61.0,57.0,353,3.94,3.96,2.41
23,24,0.31,Very Good,J,SI1,59.4,62.0,353,4.39,4.43,2.62
24,25,0.31,Very Good,J,SI1,58.1,62.0,353,4.44,4.47,2.59
25,26,0.23,Very Good,G,VVS2,60.4,58.0,354,3.97,4.01,2.41
26,27,0.24,Premium,I,VS1,62.5,57.0,355,3.97,3.94,2.47
27,28,0.30,Very Good,J,VS2,62.2,57.0,357,4.28,4.30,2.67
28,29,0.23,Very Good,D,VS2,60.5,61.0,357,3.96,3.97,2.40
29,30,0.23,Very Good,F,VS1,60.9,57.0,357,3.96,3.99,2.42
...,...,...,...,...,...,...,...,...,...,...,...
53910,53911,0.70,Premium,E,SI1,60.5,58.0,2753,5.74,5.77,3.48
53911,53912,0.57,Premium,E,IF,59.8,60.0,2753,5.43,5.38,3.23
53912,53913,0.61,Premium,F,VVS1,61.8,59.0,2753,5.48,5.40,3.36
53913,53914,0.80,Good,G,VS2,64.2,58.0,2753,5.84,5.81,3.74
53914,53915,0.84,Good,I,VS1,63.7,59.0,2753,5.94,5.90,3.77
53915,53916,0.77,Ideal,E,SI2,62.1,56.0,2753,5.84,5.86,3.63
53916,53917,0.74,Good,D,SI1,63.1,59.0,2753,5.71,5.74,3.61
53917,53918,0.90,Very Good,J,SI1,63.2,60.0,2753,6.12,6.09,3.86
53918,53919,0.76,Premium,I,VS1,59.3,62.0,2753,5.93,5.85,3.49
53919,53920,0.76,Ideal,I,VVS1,62.2,55.0,2753,5.89,5.87,3.66
53920,53921,0.70,Very Good,E,VS2,62.4,60.0,2755,5.57,5.61,3.49
53921,53922,0.70,Very Good,E,VS2,62.8,60.0,2755,5.59,5.65,3.53
53922,53923,0.70,Very Good,D,VS1,63.1,59.0,2755,5.67,5.58,3.55
53923,53924,0.73,Ideal,I,VS2,61.3,56.0,2756,5.80,5.84,3.57
53924,53925,0.73,Ideal,I,VS2,61.6,55.0,2756,5.82,5.84,3.59
53925,53926,0.79,Ideal,I,SI1,61.6,56.0,2756,5.95,5.97,3.67
53926,53927,0.71,Ideal,E,SI1,61.9,56.0,2756,5.71,5.73,3.54
53927,53928,0.79,Good,F,SI1,58.1,59.0,2756,6.06,6.13,3.54
53928,53929,0.79,Premium,E,SI2,61.4,58.0,2756,6.03,5.96,3.68
53929,53930,0.71,Ideal,G,VS1,61.4,56.0,2756,5.76,5.73,3.53
53930,53931,0.71,Premium,E,SI1,60.5,55.0,2756,5.79,5.74,3.49
53931,53932,0.71,Premium,F,SI1,59.8,62.0,2756,5.74,5.73,3.43
53932,53933,0.70,Very Good,E,VS2,60.5,59.0,2757,5.71,5.76,3.47
53933,53934,0.70,Very Good,E,VS2,61.2,59.0,2757,5.69,5.72,3.49
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

Expected Result:

![alt text](https://drive.google.com/uc?id=1BvgM5mJEVfj0fllrjkBfQwn0QIFkry_t)

<h2>Soal 3: DataFrame vs Series</h2>

- Apa perbedaan Series dengan list dan dictionary
- Apa perbedaan dataframe dan series
- Buatlah suatu data series

Jawab:

# Perbedaan Series dengan List dan dictionary
Series menampilkan index dan nilainya, index tidak hanya bertipe integer. sedangkan 
List menampilkan nilainya saja

Series bisa memiliki key yang duplikat, dan mampu slicing data. sedangkan 
Dictionary tidak bisa memiliki key yang sama, tidak mampu slicing data

# Perbedaan dataframe dan series
DataFrame berstruktur 2 dimensi yang memiliki index colum dan index baris
Series berstruktur 1 dimensi saja atau 1 index

In [14]:
# code here
import pandas as pd
hari=['Senin', 'Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu']
pd.Series(hari)

0     Senin
1    Selasa
2      Rabu
3     Kamis
4     Jumat
5     Sabtu
6    Minggu
dtype: object

<h2>Soal 4: Pemeriksaan Data Sederhana</h2>

Di soal no 2 kamu telah membaca data tentang diamonds. pada soal ini cobalah suatu metode dari pandas untuk mengetahui beberapa data pertama dan beberapa data terakhir. kemudian sebutkan nilai dari:
- baris pertama dari column price
- baris terakhir dari column color

tunjukan cara kalian menemukan nilai tersebut di block di bawah ini.

In [30]:
# code here
data.head(1)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43

In [31]:
data.tail(1)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [40]:
price1=data['price']
p=price1.head(1)
print('Baris pertama dari column price adalah',p.values)

color1=data['color']
c=color1.tail(1)
print('Baris terakhir dari column color adalah',c.values)

Baris pertama dari column price adalah [326]
Baris terakhir dari column color adalah ['D']

<h2>Soal 5: Deskriptif Statistik</h2>

Jelaskan apa itu deskriptis statistik!

Jawab:

Statistika deskriptif merupakan suatu metode yang berhubungan dengan pengumpulan atau penyajian data sampai memberi informasi yang berguna, yang disajikan dalam bentuk tabel, diagram, grafik dan lainnya.
Informasi yang di dapatkan yang berasal dari statistika deskriptif ini antara lain ukuran pemusatan data, ukuran penyebaran data, dan juga kecenderungan suatu gugus data.

<h2>Soal 6: Practice Deskriptif Statistik</h2>

- Gunakan suatu metode dari pandas untuk mengetahui deskriptif statistik dari suatu data
- Berapa nilai rata-rata dari column price
- Berapa nilai standar deviasi dari column depth
- Berapa nilai maximum dari column carat

In [22]:
# code here
data.describe()

,Unnamed: 0,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,26970.500000,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,15571.281097,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,1.000000,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,13485.750000,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,26970.500000,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,40455.250000,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,53940.000000,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

Jawab:

In [29]:
price=data.price
print('nilai rata-rata dari column price adalah',price.mean())
depth=data.depth
print('nilai standar deviasi dari column depth adalah',depth.std())
mc=data.carat
print('nilai maximum dari column carat adalah',mc.max())

nilai rata-rata dari column price adalah 3932.799721913237
nilai standar deviasi dari column depth adalah 1.4326213188337733
nilai maximum dari column carat adalah 5.01